enhanced check

diff --git a/bootstrap b/bootstrap
--- a/bootstrap
+++ b/bootstrap
@@ -28,12 +28,13 @@ function linking() {
 echo '[-] linking dotfiles [-]'
 linking  # link first to avoid any potential issues
 
-if [[ "$OSTYPE" == "darwin"* ]]; then  # macos
-  ! xcode-select -p &> /dev/null && \
-    echo '[-] installing xcode command line tools [-]' && \
+if [ "$(uname -s)" = "Darwin" ]; then  # macos
+  if ! xcode-select -p &> /dev/null; then
+    echo '[-] installing xcode command line tools [-]'
     xcode-select --install
+  fi
 
-  if ! hash brew &> /dev/null; then
+  if ! command -v brew &> /dev/null; then
     echo '[-] installing homebrew [-]'
     /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
     (echo; echo 'eval "$(/opt/homebrew/bin/brew shellenv)"') >> ~/.zprofile
@@ -47,8 +48,7 @@ if [[ "$OSTYPE" == "darwin"* ]]; then  # macos
 else  # linux or wsl
   echo '[-] checking secure boot state [-]' && \
     [ ! -f /etc/wsl.conf ] && [[ "$(mokutil --sb-state)" != *"SecureBoot enabled"* ]] && \
-    echo "could not determine the secure boot state." && \
-    exit 1
+    echo "could not determine the secure boot state." && exit 1
 
   echo '[-] installing essential packages [-]'
   sudo apt-get update && sudo apt-get upgrade -y
